### ISSUE TITLE
`styles` missing in npm package?

### ISSUE THREAD

**Issue by kgajowy** [maluramichael/ra-input-markdown#2]
Hello there!

Thank you a lot for contributing this package, it seems great!

However, I have the following issue:
```
./node_modules/ra-input-markdown/lib/index.js
Module not found: Can't resolve './styles' in  (...)
```

Which seems to be valid error message:
![image](https://user-images.githubusercontent.com/3466388/59360614-b53aff80-8d30-11e9-97ee-f93bde8955f5.png)

I have taken a look at tsconfig but I couldn't see why `styles.js` is not included. It seems to be quite empty and just copy-paste to `lib` dir makes it work as expected.

Would be happy to contribute the fix but most likely need some advice :(

**Comment by maluramichael** [comment]
Thank you @kgajowy for the issue. I fixed it by removing the styles.js. It was empty anyway and not needed. Version 1.0.2 has the fix.

Would be great if you close this issue when its working.
