### ISSUE TITLE
Are there plans to support current versions of React?

### ISSUE THREAD

**Issue by JazzShapka** [maluramichael/ra-input-markdown#20]
This is an important project for my team and we would like to continue to use it.
But for version 17.0.2 I get the error `Minified React error #188` on almost every hover event.

Thanks.

**Comment by maluramichael** [comment]
Hey @JazzShapka. Sorry for the late anwser. I updated the react and react-dom dependencies to 17.0.2 and rebuilded. I did not see any errors for now and will push the update to npm. Would be nice to hear back from you if it worked.

**Comment by JazzShapka** [comment]
> Hey @JazzShapka. Sorry for the late anwser. I updated the react and react-dom dependencies to 17.0.2 and rebuilded. I did not see any errors for now and will push the update to npm. Would be nice to hear back from you if it worked.

Thank you. Works fine!
