### ISSUE TITLE
Version 1.0.2 module not found

### ISSUE THREAD

**Issue by b3nab** [maluramichael/ra-input-markdown#7]
There isn't a lib folder in the node_modules/ra-input-markdown, maybe you forget to build before release a version of this npm package? :D

Actual "hacky" workaround is:
```
cd node_modules/ra-input-markdown && yarn && yarn build
```

**Comment by maluramichael** [comment]
Hey @b3nab thank you for the issue. The latest version should contain the lib dir now.

**Comment by b3nab** [comment]
Yes, nice job and thanks @maluramichael !

🥂
