### ISSUE TITLE
Why use it as a devDependency?

### ISSUE THREAD

**Issue by Vadorequest** [maluramichael/ra-input-markdown#8]
![image](https://user-images.githubusercontent.com/3807458/76304153-2b21c680-62c3-11ea-8799-cdca0a87aff1.png)

This seems wrong, it should be installed as a dep, not a devDep.

**Comment by maluramichael** [comment]
Good point. Ill change it.

**Comment by maluramichael** [comment]
https://github.com/maluramichael/ra-input-markdown/commit/16be7e1463887c136c8d7ec44aa1be3f2cfbcb77 fixed this. Thank you for the issue.

**Comment by Vadorequest** [comment]
Nice, that was fast!
